name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build check
        run: cmake --build build -j$(nproc)
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cppcheck
        run: cmake --build build -j$(nproc) --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: build/cppcheck_report.xml
  uncrustify:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Crust check
        run: cmake --build build -j$(nproc) --target uncrustify-check
      - name: Upload Uncrustify Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: uncrustify-report
          path: build/uncrustify_report.txt
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build tests
        run: cmake --build build -j$(nproc) --target CAVeTalk-tests-cpp
      - name: Run tests
        run: cmake --build build -j$(nproc) -t test --verbose
      - name: Upload unit tests log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-log
          path: build/Testing/Temporary/LastTest.log