name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Setup
        uses: CAVEMaN-SeniorDesign/CAVeTalk/.github/workflows/action.yml
      - name: Build check
        run: cmake --build build -j$(nproc)
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache Protobuf CMake files
        id: cache-protobuf-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-protobuf-cmake
        with:
          path: ./external/protobuf/_build
          key: ${{ env.cache-name }}-${{ hashFiles('./external/protobuf/**/*') }}
      - name: Generate Protobuf CMake cache
        if: ${{ steps.cache-protobuf-cmake.outputs.cache-hit != 'true' }}
        run: |
          cd ./external/protobuf/
          cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_build/protobuf-install -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -DABSL_PROPAGATE_CXX_STD=ON -G Ninja
          cmake --build _build --config Release
          cmake --build _build -t install
          cd ../../
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Cppcheck
        run: cmake --build build -j$(nproc) --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: build/cppcheck_report.xml
  uncrustify:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache Protobuf CMake files
        id: cache-protobuf-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-protobuf-cmake
        with:
          path: ./external/protobuf/_build
          key: ${{ env.cache-name }}-${{ hashFiles('./external/protobuf/**/*') }}
      - name: Generate Protobuf CMake cache
        if: ${{ steps.cache-protobuf-cmake.outputs.cache-hit != 'true' }}
        run: |
          cd ./external/protobuf/
          cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_build/protobuf-install -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -DABSL_PROPAGATE_CXX_STD=ON -G Ninja
          cmake --build _build --config Release
          cmake --build _build -t install
          cd ../../
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Crust check
        run: cmake --build build -j$(nproc) --target uncrustify-check
      - name: Upload Uncrustify Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: uncrustify-report
          path: build/uncrustify_report.txt